### ISSUE TITLE
debian mipsel build issues

### ISSUE THREAD

**Issue by aborrero** [pgbovine/CDE#15]
Hi there!

It seems there are some issues regarding the build of CDE on debian mipsel. 

See the build log here: https://buildd.debian.org/status/fetch.php?pkg=cde&arch=mipsel&ver=0.1%2Bgit9-g551e54d-1&stamp=1384849519

Particularly:
```
In file included from strace.c:40:0:
defs.h:437:27: error: field 'saved_regs' has incomplete type
   struct user_regs_struct saved_regs;
                           ^
```

Is there any hint you could give me to solve the issue?

Thanks, best regards.

**Comment by pgbovine** [comment]
sorry i have no clue :( this project hasn't been maintained in over 4 years. best wishes, though!
